#!/bin/sh

toilet osu\!
echo launcher by jvyden420
echo

export WINEPREFIX="$HOME/osu"
export WINEARCH=win32
export STAGING_AUDIO_DURATION=2000

if [ $# -eq 0 ]
	then
		killall baloo_file           #Kill processes that are useless
		killall baloo_file_extractor #and use up resources on my system.
		cd ~/osu/drive_c/osu
		xinput map-to-output 26 HDMI-0 # This line is specific to me. You can remove this if you'd like.
		echo "If your game doesn't start, try running 'osu kill'."
		wine osu\!.exe "$@"
fi
if [ $# -ne 0 ] # OMG JVYDEN USE CASES SMH BAD PROGRAMMER
then
	if [ $1 = beatmap ] # If you have supporter, this is useless to you.
	then
		echo "Moving all .osz files to songs folder..."
		mv ~/Downloads/*.osz ~/osu/drive_c/osu/Songs/
		echo $?
		if [ $? -eq 0 ]
		then
			echo "Done."
		else
			echo "Nothing to move."
		fi
		exit
	fi
	if [ $1 = kill ] # Useful when your game is stuck.
	then
		echo "Killing osu!..."
		wineserver -k "$@"
		wineserver -w "$@"
		echo "Done."
		exit
	fi
	if [ $1 = run ] # Useful for running winecfg in osu's prefix.
	then
		echo Running $2...
		wine $2 "$@"
	fi
fi
echo
toilet osu\!
echo
echo launcher by jvyden420
echo
echo see you next time
