#!/bin/sh

echo '                        m   
  mmm    mmm   m   m    #   
 #" "#  #   "  #   #    #   
 #   #   """m  #   #    "   
 "#m#"  "mmm"  "mm"#    # '
echo launcher by jvyden420
echo

export WINEPREFIX="$HOME/osu"
export WINEARCH=win32
export STAGING_AUDIO_DURATION=2000

if [ $# -eq 0 ]
	then
		cd ~/osu/drive_c/osu
		sh ~/.config/osu.sh
		echo "If your game doesn't start, try running 'osu kill'."
		wine osu\!.exe "$@"
fi
if [ $# -ne 0 ] # OMG JVYDEN USE CASES SMH BAD PROGRAMMER
then
	if [ $1 = beatmap ] # If you have supporter, this is useless to you.
	then
		echo "Moving all .osz files to songs folder..."
		mv ~/Downloads/*.osz ~/osu/drive_c/osu/Songs/
		echo $?
		if [ $? -eq 0 ]
		then
			echo "Done."
		else
			echo "Nothing to move."
		fi
		exit
	fi
	if [ $1 = kill ] # Useful when your game is stuck.
	then
		echo "Killing osu!..."
		wineserver -k "$@"
		wineserver -w "$@"
		echo "Done."
		exit
	fi
	if [ $1 = run ] # Useful for running winecfg in osu's prefix.
	then
		echo Running $2...
		wine $2 "$@"
	fi
fi
echo
echo '                        m   
  mmm    mmm   m   m    #   
 #" "#  #   "  #   #    #   
 #   #   """m  #   #    "   
 "#m#"  "mmm"  "mm"#    # '
echo
echo launcher by jvyden420
echo
echo see you next time
